#!/bin/bash
#
#   $ ./build_spark
#
set -e
set -u

EXPECTED_ARGS=0
E_BADARGS=65

if [ $# -lt $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0`"
  exit ${E_BADARGS};
fi

function lsb_release_tag {
  lsb_release --id --release | cut -d: -f2 | tr A-Z a-z | xargs | tr ' ' '/'
}

function get_codename {
  case "$(lsb_release_tag)" in
    ubuntu/*|debian/*)
      lsb_release -c | cut -d: -f2 | tr A-Z a-z | xargs | tr ' ' '/'
    ;;
    centos/*|redhat/*)
      err "not implemented yet"
    ;;
    *)                 err "Not sure how to configure logrotate for: $linux" ;;
  esac
}

function architecture {
  case "$(lsb_release_tag)" in
    ubuntu/*|debian/*) dpkg-architecture -qDEB_BUILD_ARCH ;;
    centos/*|redhat/*) arch ;;
    *)                 err "Not sure how to determine arch for: $linux" ;;
  esac
}

function get_system_info {
  linux="$(lsb_release_tag)"            # <distro>/<version>, like ubuntu/12.10
  arch="$(architecture)"          # In the format used to label distro packages
  codename="$(get_codename)"
}


name=spark-mesos
CODENAME="$(get_codename)"
VERSION=0.8.0
DEB_BUILD_ARCH="$(architecture)"
LICENSE="Apache License 2.0"
description="Spark is an open source cluster computing system that aims to make data analytics fast — both fast to run and fast to write. To run programs faster, Spark provides primitives for in-memory cluster computing: your job can load data into memory and query it repeatedly much more quickly than with disk-based systems like Hadoop MapReduce."
url="http://spark-project.org/"
arch="${DEB_BUILD_ARCH}"
section="misc"
package_version=""
origdir="$(pwd)"


# add e.g. to ~/.bash_profile 'export MAINTAINER="your@email.com"'
# if variable not set, use default value
if [[ -z ${MAINTAINER+xxx} && "${MAINTAINER+xxx}" = "xxx" ]]; then
  #variable is not set at all or it's empty
  MAINTAINER="${USER}@localhost"
fi

#_ MAIN _#
echo "removing ${name}*.deb"
rm -rf ${name}*.deb
mkdir -p tmp && pushd tmp

#check dependencies
DEPENDENCIES=(scala maven)
i=0
expstatus="Status: install ok installed"
for package in ${DEPENDENCIES[@]}
do
   status=`dpkg -s ${package} | grep Status:`
   if [[ "${status}" != *"${expstatus}"* ]]; then
     echo "missing package: ${package}"
     i=$((i+1))
   fi
done
if [[ i -gt 0 ]]; then
  echo "please install missing dependencies"
  exit 1
fi

REPO="spark"
if [ ! -d ${REPO}/.git ]; then
  rm -rf ${REPO}
  git clone git://github.com/apache/incubator-spark.git
  cd ${REPO}
else
  cd ${REPO}
  git pull
  git --no-pager log --pretty=format:"%h%x09%an%x09%ad%x09%s" --decorate --graph > CHANGELOG
fi
#short hash tag for build identification
LASTCOMMIT=`git rev-parse --short HEAD`


mvn -DskipTests -Phadoop2,deb install



