#!/bin/bash
VERSION="1.0.2" #version must start with a number
BRANCH="v1.0.2"
PATCH=$1
DIST="trusty"
cmd="./build_spark --repo https://git-wip-us.apache.org/repos/asf/spark.git?ref=${BRANCH} --version ${VERSION}${PATCH}"
echo $cmd
($cmd)

